# Generated by Django 4.0.4 on 2022-05-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_match_nb_goals_match_nb_red_cards_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='MatchAVenir',
        ),
    ]
