# Generated by Django 4.0.4 on 2022-05-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_matchstermines_rename_matchavenir_matchsavenir'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchsTermines',
            new_name='MatchsTermine',
        ),
    ]
