# Generated by Django 4.0.4 on 2022-05-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='datas',
        ),
        migrations.AddField(
            model_name='data',
            name='championship',
            field=models.CharField(default='01', max_length=200),
            preserve_default=False,
        ),
    ]
