# Generated by Django 4.0.4 on 2022-05-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_name_iframe_championship_iframe_iframe_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchsavenir',
            name='nb_goals',
        ),
        migrations.RemoveField(
            model_name='matchsavenir',
            name='nb_red_cards',
        ),
        migrations.RemoveField(
            model_name='matchsavenir',
            name='nb_yellow_cards',
        ),
        migrations.AddField(
            model_name='matchsavenir',
            name='card_bet',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
