# Generated by Django 4.0.4 on 2022-05-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_matchsavenir_nb_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iframe',
            name='date_updated',
            field=models.CharField(max_length=200),
        ),
    ]
