# Generated by Django 4.0.4 on 2022-05-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_iframe_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='datas_stats',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
