# Generated by Django 4.0.4 on 2022-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_data_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstermine',
            name='card_bet',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchstermine',
            name='score',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
