# Generated by Django 4.0.4 on 2022-05-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_matchstermine_double_chance_predict'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamIframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('iframe_url', models.URLField()),
                ('iframe_stats', models.CharField(max_length=200)),
                ('date_updated', models.CharField(max_length=200)),
            ],
        ),
    ]
