# Generated by Django 4.0.4 on 2022-05-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_nb_goals_matchstermine_corner_against_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchstermine',
            name='championship',
        ),
    ]
