# Generated by Django 4.0.4 on 2022-05-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_matchstermine_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchsavenir',
            name='double_chance_predict',
        ),
        migrations.AddField(
            model_name='matchsavenir',
            name='corner_bet',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
