# Generated by Django 4.0.4 on 2022-05-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_matchsavenir_double_chance_predict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsavenir',
            name='away_team_corners_against_average',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsavenir',
            name='away_team_corners_for_average',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsavenir',
            name='home_team_corners_against_average',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsavenir',
            name='home_team_corners_for_average',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
