# Generated by Django 4.0.4 on 2022-05-10 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_matchstermines_matchstermine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('iframe_url', models.URLField()),
                ('date_updated', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
