# Generated by Django 4.0.4 on 2022-05-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_name_data_datas_data_championship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iframe',
            old_name='name',
            new_name='championship',
        ),
        migrations.AddField(
            model_name='iframe',
            name='iframe_stats',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
    ]
