# Generated by Django 4.0.4 on 2022-05-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_data_datas_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date_updated',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
