# Generated by Django 4.0.4 on 2022-05-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_matchstermine_card_bet_matchstermine_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsavenir',
            name='away_team_cards_against_average',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsavenir',
            name='away_team_cards_for_average',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsavenir',
            name='home_team_cards_against_average',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchsavenir',
            name='home_team_cards_for_average',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
