# Generated by Django 4.0.4 on 2022-05-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_matchsavenir_double_chance_predict_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstermine',
            name='double_chance_predict',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
