# Generated by Django 4.0.4 on 2022-05-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_matchstermine_double_chance_predict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstermine',
            name='double_chance_predict',
            field=models.CharField(max_length=10),
        ),
    ]
