# Generated by Django 4.0.4 on 2022-05-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_teamiframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchstermine',
            old_name='nb_goals',
            new_name='corner_against',
        ),
        migrations.RemoveField(
            model_name='matchstermine',
            name='card_bet',
        ),
        migrations.RemoveField(
            model_name='matchstermine',
            name='double_chance_predict',
        ),
        migrations.RemoveField(
            model_name='matchstermine',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchstermine',
            name='nb_red_cards',
        ),
        migrations.RemoveField(
            model_name='matchstermine',
            name='nb_yellow_cards',
        ),
        migrations.AddField(
            model_name='matchstermine',
            name='corner_for',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchstermine',
            name='red_card_against',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchstermine',
            name='red_card_for',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchstermine',
            name='target_team',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchstermine',
            name='yellow_card_against',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchstermine',
            name='yellow_card_for',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
